name: Publish docs to GitHub Pages

on:
  push:

jobs:
  build:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run docs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v1
        with:
          name: docs
          path: ./docs
      - name: Deploy Documentation to github Pages
        id: deployment
        uses: actions/deploy-pages@v2
